#!/bin/bash
# Provides:          ShadowsocksR
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lightweight SOCKS5 proxy tool
# Description:       Start or stop the ShadowsocksR mudbjson server
# =====================================================================

# ShadowsocksR mudbjson Service
NAME="ShadowsocksR"
NAME_BIN="server.py"
FOLDER="/etc/tridebleng/ssr-server/"
BIN="/etc/tridebleng/ssr-server/server.py"

# Color Validate
IJAU="\033[32m" 
MERAH="\033[31m"
NC="\033[0m"

RETVAL=0

check_running(){
	PID=`ps -ef |grep "${NAME_BIN}" |grep -v "grep" |grep -v "init.d" |grep -v "service" |awk '{print $2}'`
	if [[ ! -z ${PID} ]]; then
		return 0
	else
		return 1
	fi
}
do_start(){
	check_running
	if [[ $? -eq 0 ]]; then
	echo -e "[$IJAU OK $NC] $NAME (PID ${PID}) Running & No Eror..." && exit 0
	else
		cd ${FOLDER}
		python_ver="python"
		ulimit -n 512000
		nohup "${python_ver}" "$BIN" a >> /etc/tridebleng/ShadowsocksR-Server.log 2>&1 &
		sleep 2s
		check_running
		if [[ $? -eq 0 ]]; then
			echo -e "[$IJAU OK $NC] $NAME Succesfull Started !"
		else
			echo -e "[${MERAH} EROR ${NC}] $NAME Failed Started !"
		fi
	fi
}
do_stop(){
	check_running
	if [[ $? -eq 0 ]]; then
		kill -9 ${PID}
		RETVAL=$?
		if [[ $RETVAL -eq 0 ]]; then
			echo -e "[$IJAU OK $NC] $NAME Successfull Stoped !"
		else
			echo -e "[${MERAH} EROR ${NC}] Failed Stoping $NAME !"
		fi
	else
		echo -e "[${MERAH} EROR ${NC}] $NAME Eror | Not Running !"
		RETVAL=1
	fi
}
do_status(){
	check_running
	if [[ $? -eq 0 ]]; then
		echo -e "[$IJAU OK $NC] $NAME (PID ${PID}) Running.."
	else
		echo -e "[${MERAH} EROR ${NC}] $NAME Not Running !"
		RETVAL=1
	fi
}
do_restart(){
	do_stop
	do_start
}
case "$1" in
	start|stop|restart|status)
	do_$1
	;;
	*)
	echo "/etc/init.d/ssr-server + { start | stop | restart | status }"
	RETVAL=1
	;;
esac
exit $RETVAL